### PR TITLE
[WIP] Adding graph to leaderboard pages

### PR DESCRIPTION
**Pull request by lotusgraham**

### CODE REVIEW

**Comment by ckcollab** [comment]
Semi-blocked on some features from "force best to leaderboard" branch

**Comment by Tthomas63** [comment]
single_csv

Single CSV FIle

all_csv

All CSV Files from list

choice_csv

Choice CSV Files from list

https://github.com/codalab/codalab-competitions/pull/1731/commits/3881f1a5e473f96e99e01eed2ec6d770a0c9f74d

**Comment by ckcollab** [comment]
@Tthomas63 just noting that we need to pull out the "large csv dataset" changes and move those to a temporary branch. After that's done, we need to fix these conflicts.

**Comment by Tthomas63** [comment]
https://github.com/codalab/codalab-competitions/pull/1731 

@ckcollab removes all but one .CSV, reverts back to the old chart code, but I also kept a copy of my chart code with reading from the .CSV's.

**Comment by ckcollab** [comment]
You can check the files tab to see all the changes still in this branch, I think there's still a bit left in this branch to move over?

**Comment by Tthomas63** [comment]
@ckcollab I think I got them all now. Unless you want me to move csv_parser.py as well and remove the code for that ( Most of it already is )

**Comment by ckcollab** [comment]
Yeah please move that to a special test branch (think you already made one)

**Comment by ckcollab** [comment]
@Tthomas63 please check this out, test it, and then if it's working fine we can merge!

**Comment by Tthomas63** [comment]
@ckcollab I looked over this branch and it is working.

**Pull request merged**
