### PR TITLE
Front page customization & recent changes

### PR DESCRIPTION
**Pull request by ckcollab**
# A brief description of the purpose of the changes contained in this PR.
Add ability to edit front page message and merge in recent changes

# A checklist for hand testing
- [x] can go to admin page http://localhost/admin/customizer/configuration/1/ (if you go to the front page it's under `Customizer -> Configuration`) and changes appear on front page.
- [x] if front page message is empty nothing is displayed
- [x] if front page message contains XSS they are replaced/sanitized properly (i.e. ``)
- [x] can uncomment the "* If we want to do huge maintenance again, can use this warning!" code and see a maintenance warning
    - [x] Once you deal with maintenance warning it stops bothering you (remembers your selection)
- [x] CircleCI tests are fixed

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] Ready to merge

### CODE REVIEW

**Comment by ckcollab** [comment]
@Didayolo merging this will fix the failing test here in #2758

**Comment by Didayolo** [comment]
Nice, I'll review that ASAP.

**Comment by Didayolo** [comment]
This is great, it even sanitize error from the HTML code (unclosed HTML tag, etc.)

The only thing is that there is no link on this menu to the `customizer/configuration` or at least to the `admin` interface:

codalab-menu

**Comment by ckcollab** [comment]
> This is great, it even sanitize error from the HTML code (unclosed HTML tag, etc.)

ty :)

> The only thing is that there is no link on this menu to the customizer/configuration or at least to the admin interface:

Added to "customize codalab" page!

**Comment by Didayolo** [comment]
> Added to "customize codalab" page!

Cool, I find it really more convenient this way.

**Pull request merged**
