### PR TITLE
Solving partially #1607 (OSError: [Errno 39] Directory not empty)

### PR DESCRIPTION
**Pull request by julsal**
According to the post below, the "Directory not empty" error occurs because shutil.rmtree can't delete files set as read-only. The suggested solution was added in order to solve this problem.

IMPORTANT: Unfortunately, I don't have a Windows environment to fully test.

http://stackoverflow.com/questions/4829043/how-to-remove-read-only-attrib-directory-with-python-in-windows

### CODE REVIEW

**Comment by FlavioAlexander** [comment]
@julsal Even though this PR will solve the problem you mentioned above. I am afraid that the root of our problem is different. I have done some digging into this matter myself and found that  `.fuse_hidden files` are created, reason why `shutil.rmtree` won't be able to remove them. I have used `lsof` to find which process is using this file without any luck. The only thing that seems to work is `stopping/starting` the python process.

**Comment by julsal** [comment]
I understand. In my case, 100% of the submissions fail with this error. My python code has more than one files. Do you think there is any relation to that? If you have difficulties to reproduce the problem, I can share my case with you.

**Comment by FlavioAlexander** [comment]
@julsal I have never seen this error locally. Could you walk me through your set up? What OS are you  running on? If your machine is Windows, then your solution might work. Sorry for the late response :)

**Comment by julsal** [comment]
@FlavioAlexander Just to make it clear, I didn't run the server on my side. I've just faced the error using it. If it still matters, I'm submitting from Ubuntu. If it helps, my suggestion was to share with you my competition metadata to allow you to reproduce the error.

**Comment by FlavioAlexander** [comment]
@julsal Thanks for the clarification. What do you mean with your python code has more than one file? That shouldn't be a problem honestly. Is your competition being hosted on codalab server? Where is your competition hosted?

**Comment by julsal** [comment]
@FlavioAlexander It means that my python script calls other python scripts present in the same directory. Yes, my competition is hosted on codalab server. It is this one: https://competitions.codalab.org/competitions/15363?secret_key=cfb32c59-5791-454f-be9f-b7c0013fed58

I just check the results and found out that the last submission succeeded.

**Comment by FlavioAlexander** [comment]
@julsal Having multiple script shouldn't matter for this specific error. Please, try making more submissions and let me know that results. Recently, I set up new servers and haven't seen this error.

**Comment by julsal** [comment]
@FlavioAlexander after some tests, it seems solved. Thank you very much for your help.

**Comment by FlavioAlexander** [comment]
@julsal I am glad it is working, let me know if you have any more questions

**Pull request closed without merging**
