### PR TITLE
highlights page stats to match codabench

### PR DESCRIPTION
**Pull request by bbearce**
# @ mention of reviewers
@Didayolo 

# A brief description of the purpose of the changes contained in this PR.
Add stats for:
* Total Competitions
* Public Competitions
* Private Competitions
* Users
* Competition Participants
* Submissions

# A checklist for hand testing
- [x] Create User
- [x] Create Competition A (published or "public")
- [x] Create Competition B (Unpublished or "private")
- [x] Create Submission

# Preview
image

# Checklist
- [x] Code review by me 
- [x] Hand tested by me 
- [x] I'm proud of my work
- [x] Code review by reviewer
- [x] Hand tested by reviewer
- [x] Ready to merge

### CODE REVIEW

**Comment by bbearce** [comment]
Now that I remember, we may have talked about adding this to the front page. I can do that pretty easily and it just slipped my mind. Let me know if that is still preferred and I can do that.

**Comment by bbearce** [comment]
Example deploy here: https://codalab-python3-test.eastus.cloudapp.azure.com/highlights

**Comment by bbearce** [comment]
The spacing is an issue. I will look into that. 

Also wanted to note in Codabench the django model Q filter is:
...
            published_comps=Count('pk', filter=Q(published=True)),
            unpublished_comps=Count('pk', filter=Q(published=False)),
...
but in this PR it is:
...
            published_comps=Count(Case(When(published=True, then=1))),
            unpublished_comps=Count(Case(When(published=False, then=1)))
...
The reason is that using the Codabench query I was getting unpublished results counted in with published results. In other words published_comps was always counting unpublished comps and had the same value. This fixed it.

**Comment by Didayolo** [comment]
> The reason is that using the Codabench query I was getting unpublished results counted in with published results. In other words published_comps was always counting unpublished comps and had the same value. This fixed it.

Nice catch. Do you think then there is a problem on CodaBench side?

**Comment by bbearce** [comment]
The css for codabench and codalab is such that if the "Users" count is small the information is left aligned inside it's div. Since we aren't explicitly setting the widths of the divs in the stats section we can't use "margin: auto" to center. The reason we don't see this for other divs in the stats section is because they all have long description text. By changing "Users" to "CodaLab Site Users" we force the div to auto adjust spacing and position to create a centered look. 

Anyone who is better at css could do better but this is pretty simple and clean to me.

**Comment by Didayolo** [comment]
@bbearce 

> Live deploy here: https://codalab-python3-test.eastus.cloudapp.azure.com/highlights

This time the change is not visible in your live deploy.

**Comment by Didayolo** [comment]
That's great! I do a last round of testing and merge it

**Review by Didayolo — APPROVED** [review]

**Comment by Didayolo** [comment]
The change is now live: https://codalab.lisn.upsaclay.fr/highlights

Thank you very much @bbearce !

**Pull request merged**
