### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by Tthomas63**
Update master branch

### CODE REVIEW

**Comment by Didayolo** [comment]
@Tthomas63 We basically want to replace the conflicting files by the `develop` version, right?

**Comment by Tthomas63** [comment]
@Didayolo Not always, but for most of everything in this case yes. There was some differences on the highlights page, and I left the master branch's version of the different URL's commented out. That page is going to see work soon regardless

**Comment by Didayolo** [comment]
@Tthomas63 Great work! Indeed I've seen the changes you are referring too. 

I guess this need hand-testing before merging. I'll try out soon.

**Comment by loicsarrazin** [comment]
After verifying https://github.com/codalab/codalab-competitions/pull/3032/commits/05f79831b84a6b3b5af681ae6f137d74811cb179, that should be the only differences to develop, are not breaking the impacted views. I'm ok with merging this PR.

**Comment by Didayolo** [comment]
I've also checked the code and tested manually, and everything seems good to go!

**Pull request merged**
